const cars=[
 {make:"BMW",model:"M340i",engine:"B58",hp:382,img:"https://commons.wikimedia.org/wiki/Special:FilePath/2020_BMW_M340i_xDrive_in_Black_Sapphire_Metallic,_rear_left.jpg"},
 {make:"Toyota",model:"GR Supra",engine:"B58",hp:382,img:"https://commons.wikimedia.org/wiki/Special:FilePath/2020_Toyota_GR_Supra_(United_States).png"},
 {make:"Volkswagen",model:"Golf GTI",engine:"EA888",hp:241,img:"https://upload.wikimedia.org/wikipedia/commons/d/d8/Volkswagen_Golf_VIII_GTI_IMG_3604.jpg"},
 {make:"Audi",model:"RS3",engine:"EA855",hp:401,img:"https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?auto=format&fit=crop&w=1000&q=80"},
 {make:"Nissan",model:"GT-R",engine:"VR38DETT",hp:565,img:"https://commons.wikimedia.org/wiki/Special:FilePath/2018_Nissan_GT-R_Premium_in_Super_Silver,_Front_Right,_10-11-2022.jpg"},
 {make:"Honda",model:"Civic Type R",engine:"K20C1",hp:306,img:"https://commons.wikimedia.org/wiki/Special:FilePath/2018_Honda_Civic_GT_Type_R_VTEC_2.0_Front.jpg"},
 {make:"Ford",model:"Mustang GT",engine:"Coyote 5.0",hp:460,img:"https://commons.wikimedia.org/wiki/Special:FilePath/2019_Ford_Mustang_GT_5.0_facelift.jpg"},
 {make:"Tesla",model:"Model 3 Performance",engine:"Dual Motor EV",hp:450,img:"https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1000&q=80",ev:true}
];
const stepsIce=[["Inspection","Service, scan, logs"],["Base Setup","ECU baseline + calibration"],["Cooling","Intercooler and temps"],["Airflow","Intake + exhaust"],["Grip & Brakes","Tires, pads, fluid"],["Final Validation","Test, inspect, refine"]];
const stepsEv=[["Inspection","Tires, brakes, suspension"],["Grip","Tires and alignment"],["Brakes","Pads, fluid, rotors"],["Thermal","Battery and drive temps"],["Validation","Repeatable performance"]];
function norm(v){return String(v||"").toLowerCase().replace(/[^a-z0-9]/g,"")}
function fallback(img){img.onerror=()=>{img.src="https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1000&q=80"}}
function pickCar(){const p=new URLSearchParams(location.search);return cars.find(c=>norm(c.make)===norm(p.get("make"))&&norm(c.model)===norm(p.get("model")))||cars.find(c=>norm(c.engine)===norm(p.get("engine")))||cars[0]}
function render(){
 const app=document.getElementById("roadmapApp"),p=new URLSearchParams(location.search),car=pickCar(),target=Number(p.get("targetHp"))||car.hp+100,steps=car.ev?stepsEv:stepsIce,progress=Math.round(100/steps.length);
 app.innerHTML=`<section class="build-card"><a class="back-build" href="index.html#planner">← Back to Build</a><div class="brand-row"><span class="brand-mark">${car.make.slice(0,2).toUpperCase()}</span><div><small>${car.make}</small><h1>${car.model}</h1></div></div><img src="${car.img}" alt="${car.make} ${car.model}"><p class="engine-pill">${car.engine}</p><div class="power-row"><div><small>BASE</small><strong>${car.hp} HP</strong></div><span>→</span><div><small>TARGET</small><strong>${target} HP</strong></div></div><button type="button" class="summary-btn">View Build Summary →</button></section><section class="road-stage"><div class="road-title"><h2>Build Roadmap</h2><p>Follow the path to ${target} HP.<br>Six stages. One purpose. Peak performance.</p><div class="road-chips"><span>${steps.length} STAGES</span><span>~8–10 WEEKS</span></div></div><div class="progress-card"><span>OVERALL PROGRESS</span><strong>${progress}%</strong><div class="progress-line"><i style="width:${progress}%"></i></div><p>1 of ${steps.length} stages completed</p></div><div class="road-track">${steps.map((s,i)=>`<article class="road-step" style="--step:${i}"><div class="road-pin">${String(i+1).padStart(2,"0")}</div><div class="road-card"><span>${String(i+1).padStart(2,"0")}</span><h3>${s[0]}</h3><p>${s[1]}</p></div></article>`).join("")}<div class="cockpit-frame"></div></div><div class="stage-detail"><div><strong>01 Inspection</strong><p>Baseline checks and diagnostics to ensure your car is ready.</p></div><ul><li>OBD Scan</li><li>Fluid Check</li><li>Leak Inspection</li><li>Performance Log</li></ul><button type="button">View Details →</button></div><div class="bottom-strip"><span>⚡ Target Power <b>${target} HP</b></span><span>🛡 Reliability First</span><span>🏁 Track Ready</span><span>⏱ ~8–10 Weeks</span></div></section>`;
 app.querySelectorAll("img").forEach(fallback);
}
render();
