function img(file){return `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}`}
const fallback=img("2019_Ford_Mustang_GT_5.0_facelift.jpg");
const cars=[
 {make:"BMW",model:"M340i",engine:"B58",hp:382,target:500,type:"ice",image:img("2020_BMW_M340i_xDrive_in_Black_Sapphire_Metallic,_rear_left.jpg")},
 {make:"Toyota",model:"GR Supra",engine:"B58",hp:382,target:550,type:"ice",image:img("2020_Toyota_GR_Supra_(United_States).png")},
 {make:"Volkswagen",model:"Golf GTI",engine:"EA888",hp:241,target:350,type:"ice",image:img("Volkswagen_Golf_GTI_Clubsport_IMG_0101.jpg")},
 {make:"Audi",model:"RS3",engine:"EA855",hp:401,target:560,type:"ice",image:img("Audi_RS3_Sportback_IMG_4012.jpg")},
 {make:"Nissan",model:"GT-R",engine:"VR38DETT",hp:565,target:800,type:"ice",image:img("2018_Nissan_GT-R_Premium_in_Super_Silver,_Front_Right,_10-11-2022.jpg")},
 {make:"Honda",model:"Civic Type R",engine:"K20C1",hp:306,target:420,type:"ice",image:img("2018_Honda_Civic_GT_Type_R_VTEC_2.0_Front.jpg")},
 {make:"Ford",model:"Mustang GT",engine:"Coyote 5.0",hp:460,target:700,type:"ice",image:img("2019_Ford_Mustang_GT_5.0_facelift.jpg")},
 {make:"Dodge",model:"Challenger Hellcat",engine:"Hellcat 6.2",hp:717,target:850,type:"ice",image:img("2015_HellCat.JPG")},
 {make:"Tesla",model:"Model 3 Performance",engine:"Dual Motor EV",hp:450,target:450,type:"ev",image:img("Tesla_Model_3_Performance_AWD_IMG_5678.jpg")}
];
const makes=[...new Set(cars.map(c=>c.make))];
const models=[...new Set(cars.map(c=>c.model))];
const engines=[...new Set(cars.map(c=>c.engine))];
const form=document.getElementById("tuneForm"),results=document.getElementById("results"),presets=document.getElementById("presets");
function norm(v){return String(v||"").toLowerCase().replace(/[^a-z0-9]/g,"")}
function byForm(){return cars.find(c=>norm(c.make)===norm(make.value)&&norm(c.model)===norm(model.value)&&norm(c.engine)===norm(engine.value))||cars.find(c=>norm(c.model)===norm(model.value)||norm(c.engine)===norm(engine.value))}
function safeImage(el){if(el)el.onerror=()=>{el.src=fallback}}
function roadmapUrl(car,target){const p=new URLSearchParams({make:car.make,model:car.model,engine:car.engine,currentHp:car.hp,targetHp:target||car.target});return `roadmap.html?${p}`}
function ac(inputId,dropId,opts){const input=document.getElementById(inputId),drop=document.getElementById(dropId);if(!input||!drop)return;function show(){const q=input.value.toLowerCase();drop.innerHTML="";opts.filter(o=>o.toLowerCase().includes(q)).slice(0,15).forEach(o=>{const d=document.createElement("div");d.className="dropdown-item";d.textContent=o;d.onmousedown=e=>{e.preventDefault();input.value=o;input.dispatchEvent(new Event("input",{bubbles:true}));drop.classList.remove("show")};drop.appendChild(d)});drop.classList.toggle("show",!!drop.children.length)}input.onfocus=show;input.oninput=show;document.addEventListener("click",e=>{if(!input.closest(".autocomplete")?.contains(e.target))drop.classList.remove("show")})}
function note(){let n=document.getElementById("baseHpNote");if(!n){n=document.createElement("small");n.id="baseHpNote";n.className="base-hp-note";currentHp.insertAdjacentElement("afterend",n)}return n}
function fillBase(){const car=byForm(),n=note();if(car){currentHp.value=car.hp;currentHp.readOnly=true;currentHp.classList.add("locked-hp");if(Number(targetHp.value)<=car.hp)targetHp.value=car.target;n.textContent=`Base HP loaded: ${car.hp} HP for ${car.make} ${car.model} ${car.engine}. Change target HP only.`}else{currentHp.readOnly=false;currentHp.classList.remove("locked-hp");n.textContent="Unknown combo: enter base HP manually."}}
function stage(gain,base,type){if(type==="ev")return"EV chassis roadmap";const pct=Math.round(gain/base*100);if(pct<=15)return"Stage 1";if(pct<=35)return"Stage 2";if(pct<=65)return"Stage 2+";return"Custom build"}
function partsFor(car,gain){if(car.type==="ev")return["Tires and alignment","Brake pads and fluid","Suspension setup","Battery and drive-unit temperature checks","Final validation"];
 const list=["Vehicle health check","Professional calibration","Cooling support","Tires and brakes"];
 if(gain>80)list.push("Airflow support");
 if(gain>140)list.push("Fuel and drivetrain review");
 if(gain>240)list.push("Major hardware planning");
 list.push("Final validation");return list}
function partVisual(name,type){const t=name.toLowerCase();if(type==="ev")return{title:name,image:img("Disc_brake_dsc03680.jpg"),text:"EV build step: no intake, exhaust or fuel-system parts."};if(t.includes("cool"))return{title:name,image:img("Intercooler.jpg"),text:"Cooling keeps power repeatable."};if(t.includes("air"))return{title:name,image:img("Car_exhaust_pipe.jpg"),text:"Airflow parts must match the exact car and local rules."};if(t.includes("fuel")||t.includes("drive"))return{title:name,image:img("Driveshaft.jpg"),text:"Support parts protect reliability."};if(t.includes("tire")||t.includes("brake"))return{title:name,image:img("Disc_brake_dsc03680.jpg"),text:"Grip and stopping power come before speed."};return{title:name,image:img("ECU_of_a_car.jpg"),text:"Plan this step with a qualified professional."}}
function openModal(name,type){const v=partVisual(name,type);modalImage.src=v.image;safeImage(modalImage);modalTitle.textContent=v.title;modalText.textContent=v.text;modModal.classList.add("show")}
function generatePlan(data){const car=byForm()||{make:data.make,model:data.model,engine:data.engine,hp:Number(data.currentHp),target:Number(data.targetHp),type:"ice",image:fallback};const target=Number(targetHp.value||data.targetHp);const gain=target-car.hp;if(gain<0){results.innerHTML="<h2>Target must be higher</h2><p>Choose a target above the base horsepower.</p>";return}const parts=partsFor(car,gain);results.innerHTML=`<div class="result-hero"><img src="${car.image}" alt="${car.make} ${car.model}"></div><div class="result-header"><div><h2>${car.make} ${car.model}</h2><p>${car.engine} · Base ${car.hp} HP → Target ${target} HP</p></div><span class="stage">${stage(gain,car.hp,car.type)}</span></div><div class="meta"><div><span>Gain</span><strong>+${gain} HP</strong></div><div><span>Base</span><strong>${car.hp} HP</strong></div><div><span>Target</span><strong>${target} HP</strong></div></div><div class="roadmap-cta"><a class="roadmap-button" href="${roadmapUrl(car,target)}">Open visual roadmap</a><span>Follow the build on a separate roadmap page.</span></div><h3>Build steps</h3><div class="parts">${parts.map(p=>`<button class="part" data-type="${car.type}" data-part="${p}" type="button"><strong>${p}</strong><span>Tap for notes.</span></button>`).join("")}</div>`;results.querySelectorAll("img").forEach(safeImage);results.querySelectorAll(".part").forEach(b=>b.onclick=()=>openModal(b.dataset.part,b.dataset.type))}
function load(car){make.value=car.make;model.value=car.model;engine.value=car.engine;currentHp.value=car.hp;targetHp.value=car.target;fillBase();generatePlan(car);planner.scrollIntoView({behavior:"smooth"})}
function renderPresets(){if(!presets)return;presets.innerHTML="";cars.forEach(car=>{const b=document.createElement("button");b.type="button";b.className="preset";b.style.setProperty("--image",`url("${car.image}")`);b.innerHTML=`<strong>${car.make} ${car.model}</strong><p>${car.engine}: base ${car.hp} HP → target ${car.target} HP</p>`;b.onclick=()=>load(car);presets.appendChild(b)})}
ac("make","makeDropdown",makes);ac("model","modelDropdown",models);ac("engine","engineDropdown",engines);["make","model","engine"].forEach(id=>document.getElementById(id)?.addEventListener("input",fillBase));form?.addEventListener("submit",e=>{e.preventDefault();fillBase();generatePlan({make:make.value,model:model.value,engine:engine.value,currentHp:currentHp.value,targetHp:targetHp.value})});closeModal?.addEventListener("click",()=>modModal.classList.remove("show"));modModal?.addEventListener("click",e=>{if(e.target.id==="modModal")modModal.classList.remove("show")});renderPresets();note();