function img(file){return `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}`}
const fallback="https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80";
const cars=[
 {brand:"BMW",model:"M340i",engine:"B58",hp:382,target:500,type:"ice",image:img("2020_BMW_M340i_xDrive_in_Black_Sapphire_Metallic,_rear_left.jpg")},
 {brand:"Toyota",model:"GR Supra",engine:"B58",hp:382,target:550,type:"ice",image:img("2020_Toyota_GR_Supra_(United_States).png")},
 {brand:"Volkswagen",model:"Golf GTI",engine:"EA888",hp:241,target:350,type:"ice",image:img("VW_Golf_VI_GTI_front_20100711.jpg")},
 {brand:"Audi",model:"RS3",engine:"EA855",hp:401,target:560,type:"ice",image:"https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?auto=format&fit=crop&w=900&q=80"},
 {brand:"Nissan",model:"GT-R",engine:"VR38DETT",hp:565,target:800,type:"ice",image:img("2018_Nissan_GT-R_Premium_in_Super_Silver,_Front_Right,_10-11-2022.jpg")},
 {brand:"Honda",model:"Civic Type R",engine:"K20C1",hp:306,target:420,type:"ice",image:img("2018_Honda_Civic_GT_Type_R_VTEC_2.0_Front.jpg")},
 {brand:"Ford",model:"Mustang GT",engine:"Coyote 5.0",hp:460,target:700,type:"ice",image:img("2019_Ford_Mustang_GT_5.0_facelift.jpg")},
 {brand:"Dodge",model:"Challenger Hellcat",engine:"Hellcat 6.2",hp:717,target:850,type:"ice",image:img("2015_HellCat.JPG")},
 {brand:"Tesla",model:"Model 3 Performance",engine:"Dual Motor EV",hp:450,target:450,type:"ev",image:"https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=900&q=80"}
];
const brandInput=document.getElementById("make"),modelInput=document.getElementById("model"),engineInput=document.getElementById("engine"),baseInput=document.getElementById("currentHp"),targetInput=document.getElementById("targetHp"),form=document.getElementById("tuneForm"),presets=document.getElementById("presets"),results=document.getElementById("results");
function norm(v){return String(v||"").toLowerCase().replace(/[^a-z0-9]/g,"")}
function safe(el){if(el)el.onerror=()=>{el.src=fallback}}
function filteredModels(){const b=norm(brandInput.value);return [...new Set(cars.filter(c=>!b||norm(c.brand)===b).map(c=>c.model))]}
function filteredEngines(){const b=norm(brandInput.value),m=norm(modelInput.value);return [...new Set(cars.filter(c=>(!b||norm(c.brand)===b)&&(!m||norm(c.model)===m)).map(c=>c.engine))]}
function selectedCar(){return cars.find(c=>norm(c.brand)===norm(brandInput.value)&&norm(c.model)===norm(modelInput.value)&&norm(c.engine)===norm(engineInput.value))||cars.find(c=>norm(c.brand)===norm(brandInput.value)&&norm(c.model)===norm(modelInput.value))}
function roadmapUrl(car,target){const p=new URLSearchParams({make:car.brand,model:car.model,engine:car.engine,currentHp:car.hp,targetHp:target||car.target});return `roadmap.html?${p}`}
function optionsFor(id){if(id==="make")return [...new Set(cars.map(c=>c.brand))];if(id==="model")return filteredModels();return filteredEngines()}
function ac(id,dropId){const input=document.getElementById(id),drop=document.getElementById(dropId);if(!input||!drop)return;function show(){const q=input.value.toLowerCase();drop.innerHTML="";optionsFor(id).filter(o=>o.toLowerCase().includes(q)).forEach(o=>{const d=document.createElement("div");d.className="dropdown-item";d.textContent=o;d.onmousedown=e=>{e.preventDefault();input.value=o;drop.classList.remove("show");input.dispatchEvent(new Event("change",{bubbles:true}))};drop.appendChild(d)});drop.classList.toggle("show",!!drop.children.length)}input.onfocus=show;input.oninput=show;document.addEventListener("click",e=>{if(!input.closest(".autocomplete")?.contains(e.target))drop.classList.remove("show")})}
function note(){let n=document.getElementById("baseHpNote");if(!n){n=document.createElement("small");n.id="baseHpNote";n.className="base-hp-note";baseInput.insertAdjacentElement("afterend",n)}return n}
function syncBase(){const car=selectedCar(),n=note();if(car){baseInput.value=car.hp;baseInput.readOnly=true;baseInput.classList.add("locked-hp");if(!targetInput.value||Number(targetInput.value)<=car.hp)targetInput.value=car.target;n.textContent=`Base HP: ${car.hp} HP for ${car.brand} ${car.model} ${car.engine}. Change target HP only.`}else{baseInput.readOnly=false;baseInput.classList.remove("locked-hp");n.textContent="Choose brand, model and engine to auto-fill base HP."}}
function openRoadmap(){const car=selectedCar()||{brand:brandInput.value,model:modelInput.value,engine:engineInput.value,hp:Number(baseInput.value),target:Number(targetInput.value),type:"ice"};location.href=roadmapUrl(car,Number(targetInput.value))}
function load(car){brandInput.value=car.brand;modelInput.value=car.model;engineInput.value=car.engine;baseInput.value=car.hp;targetInput.value=car.target;syncBase()}
function renderPresets(){if(!presets)return;presets.innerHTML="";cars.forEach(car=>{const b=document.createElement("button");b.type="button";b.className="preset preset-img";b.innerHTML=`<img src="${car.image}" alt="${car.brand} ${car.model}"><strong>${car.brand} ${car.model}</strong><p>${car.engine}: base ${car.hp} HP → target ${car.target} HP</p>`;b.onclick=()=>load(car);presets.appendChild(b);safe(b.querySelector("img"))})}
brandInput?.addEventListener("change",()=>{modelInput.value="";engineInput.value="";syncBase()});modelInput?.addEventListener("change",()=>{engineInput.value="";syncBase()});engineInput?.addEventListener("change",syncBase);targetInput?.addEventListener("input",()=>{});
ac("make","makeDropdown");ac("model","modelDropdown");ac("engine","engineDropdown");form?.addEventListener("submit",e=>{e.preventDefault();syncBase();openRoadmap()});if(results)results.hidden=true;renderPresets();note();